import test from 'node:test';
import assert from 'node:assert/strict';
import {Match,emptyInput,STEP,LEFT,RIGHT} from '../dist/src/engine.js';
const roster=Array.from({length:9},(_,i)=>({id:`fighter-${i}`,name:`Fighter ${i}`,power:1,speed:1,toughness:1}));
function setup(options={}){const m=new Match(roster,0,1,{mode:'local',random:()=>.3,...options});m.phase='fight';m.phaseTime=0;return m;}
function run(m,seconds,a={},b={}){for(let i=0;i<Math.ceil(seconds/STEP);i++)m.step([{...emptyInput(),...a},{...emptyInput(),...b}],STEP);}
function close(m,distance=85){m.fighters[0].x=550;m.fighters[1].x=550+distance;}

test('the opening countdown prevents movement and damage',()=>{const m=new Match(roster,0,1,{mode:'local'});run(m,1,{right:true,heavy:true});assert.equal(m.fighters[0].x,410);assert.equal(m.fighters[1].hp,100);assert.equal(m.phase,'intro');run(m,1.5);assert.equal(m.phase,'fight');});
test('movement stays inside the ring and opponents face each other',()=>{const m=setup();run(m,4,{left:true},{right:true});assert.equal(m.fighters[0].x,LEFT);assert.equal(m.fighters[1].x,RIGHT);assert.equal(m.fighters[0].facing,1);assert.equal(m.fighters[1].facing,-1);});
test('a strike has startup, one hit, and cannot repeat from a held button',()=>{const m=setup();close(m);run(m,.09,{light:true});assert.equal(m.fighters[1].hp,100);run(m,.15,{light:true});assert.equal(m.fighters[1].hp,94);run(m,1,{light:true});assert.equal(m.fighters[1].hp,94);});
test('out-of-range attacks do no damage',()=>{const m=setup();run(m,1,{heavy:true});assert.equal(m.fighters[1].hp,100);});
test('holding block absorbs a strike and consumes guard',()=>{const m=setup();close(m);run(m,.2,{}, {block:true});run(m,.3,{light:true},{block:true});assert.equal(m.fighters[1].hp,100);assert.ok(m.fighters[1].guard<100);assert.ok(m.drainEvents().some(e=>e.type==='block'));});
test('a depleted guard breaks under a heavy attack',()=>{const m=setup();close(m);m.fighters[1].guard=1;run(m,.55,{heavy:true},{block:true});assert.ok(m.fighters[1].hp<100);assert.ok(m.drainEvents().some(e=>e.type==='guardBreak'));});
test('jump applies gravity and lands at the exact floor',()=>{const m=setup();run(m,.2,{jump:true});assert.ok(m.fighters[0].z>0);assert.equal(m.fighters[0].state,'jump');run(m,1.1);assert.equal(m.fighters[0].z,0);assert.equal(m.fighters[0].vz,0);});
test('an airborne opponent above the attack volume is missed',()=>{const m=setup();close(m);m.fighters[1].z=230;m.fighters[1].vz=0;run(m,.22,{light:true});assert.equal(m.fighters[1].hp,100);});
test('finishers require a full meter, consume it, and knock down',()=>{const m=setup();close(m);run(m,.1,{special:true});assert.equal(m.fighters[0].move,null);run(m,.05);m.fighters[0].meter=100;run(m,.5,{special:true});assert.equal(m.fighters[0].meter,0);assert.equal(m.fighters[1].hp,69);assert.equal(m.fighters[1].state,'down');});
test('a throw synchronizes both fighters and lands exactly once',()=>{const m=setup();close(m);run(m,.02,{grapple:true});assert.ok(m.grapple);assert.equal(m.fighters[1].state,'grabbed');run(m,.55);assert.equal(m.fighters[1].state,'lifted');assert.ok(m.fighters[1].z>0);run(m,1.6);assert.equal(m.grapple,null);assert.equal(m.fighters[1].state,'down');assert.equal(m.fighters[1].z,0);assert.equal(m.fighters[1].hp,83);assert.equal(m.drainEvents().filter(e=>e.type==='slam').length,1);});
test('pin does not overwrite the defender pose and counts to three',()=>{const m=setup();close(m);m.fighters[1].state='down';m.fighters[1].downTime=4;m.fighters[1].hp=12;run(m,.02,{grapple:true});assert.equal(m.fighters[1].state,'pinned');run(m,2.8);assert.equal(m.phase,'roundEnd');assert.equal(m.wins[0],1);assert.equal(m.method,'PINFALL');assert.deepEqual(m.drainEvents().filter(e=>e.type==='count').map(e=>e.count),[1,2,3]);});
test('alternating attacks escapes a pin; holding one button does not',()=>{const m=setup();close(m);m.fighters[1].state='down';m.fighters[1].downTime=4;m.fighters[1].hp=40;run(m,.02,{grapple:true});for(let i=0;i<20&&m.pin;i++)run(m,.05,{},i%2?{heavy:true}:{light:true});assert.equal(m.pin,null);assert.equal(m.phase,'fight');assert.equal(m.fighters[1].state,'rise');});
test('KO transitions, resets round state and ends after two wins',()=>{const m=setup();close(m);m.fighters[1].hp=1;run(m,.3,{light:true});assert.equal(m.wins[0],1);run(m,3.2);assert.equal(m.round,2);assert.equal(m.fighters[1].hp,100);assert.equal(m.fighters[0].meter,0);run(m,2.5);close(m);m.fighters[1].hp=1;run(m,.3,{light:true});run(m,3.2);assert.equal(m.phase,'done');assert.equal(m.winner,0);assert.deepEqual(m.wins,[2,0]);});
test('timeout awards the healthier fighter and equal health is a draw',()=>{const m=setup();m.remaining=.01;m.fighters[0].hp=65;m.step();assert.equal(m.wins[1],1);const tied=setup();tied.remaining=.01;tied.step();assert.equal(tied.roundWinner,null);assert.deepEqual(tied.wins,[0,0]);});
test('CPU closes distance, attacks, and finishes a complete match',()=>{let seed=492;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const m=new Match(roster,0,1,{mode:'cpu',difficulty:'normal',random});for(let i=0;i<60*220&&m.phase!=='done';i++)m.step([emptyInput(),emptyInput()]);assert.equal(m.phase,'done');assert.equal(m.winner,1);assert.equal(m.wins[1],2);assert.ok(m.fighters.every(f=>Number.isFinite(f.x)&&f.z>=0&&f.hp>=0));});
test('every roster pairing remains finite through sustained random combat',()=>{let seed=772;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);for(let p=0;p<9;p++){const m=new Match(roster,p,(p+1)%9,{mode:'local',random});for(let i=0;i<60*60&&m.phase!=='done';i++){const commands=[0,1].map(()=>{const x=emptyInput();for(const key of Object.keys(x))x[key]=random()<.13;return x;});m.step(commands);assert.ok(m.fighters.every(f=>Number.isFinite(f.hp+f.x+f.z+f.meter)&&f.x>=LEFT&&f.x<=RIGHT&&f.z>=0&&f.hp>=0&&f.meter<=100));}}});

test('equal startup attacks trade instead of always favoring player one',()=>{const m=setup();close(m);run(m,.3,{light:true},{light:true});assert.equal(m.fighters[0].hp,94);assert.equal(m.fighters[1].hp,94);assert.equal(m.drainEvents().filter(e=>e.type==='hit').length,2);});
test('simultaneous lethal hits produce a draw',()=>{const m=setup();close(m);m.fighters.forEach(f=>f.hp=1);run(m,.3,{light:true},{light:true});assert.equal(m.roundWinner,null);assert.equal(m.method,'DOUBLE KO');assert.deepEqual(m.wins,[0,0]);});
test('an attack tapped near recovery executes once when the fighter is ready',()=>{const m=setup();run(m,.32,{light:true});run(m,.02);run(m,.02,{heavy:true});assert.equal(m.fighters[0].move,'light');run(m,.14);assert.equal(m.fighters[0].move,'heavy');assert.equal(m.drainEvents().filter(e=>e.type==='swing').length,2);});
test('a buffered attack expires if pressed too early in a long recovery',()=>{const m=setup();run(m,.05,{heavy:true});run(m,.02,{light:true});run(m,1);assert.equal(m.fighters[0].move,null);assert.equal(m.drainEvents().filter(e=>e.type==='swing').length,1);});
test('presses during hit-stop are retained without retriggering held actions',()=>{const m=setup();m.hitStop=.09;m.step([{...emptyInput(),pressed:{heavy:true}},emptyInput()]);assert.equal(m.fighters[0].move,null);run(m,.15);assert.equal(m.fighters[0].move,'heavy');assert.equal(m.drainEvents().filter(e=>e.type==='swing').length,1);});
test('grapple can be broken during its initial window without damage',()=>{const m=setup();close(m);run(m,.02,{grapple:true});run(m,.07,{}, {grapple:true});assert.equal(m.grapple,null);assert.ok(m.fighters.every(f=>f.hp===100&&f.state==='hurt'));assert.ok(m.drainEvents().some(e=>e.type==='throwBreak'));});
test('a late grapple break does not cancel the lift',()=>{const m=setup();close(m);run(m,.02,{grapple:true});run(m,.28);run(m,.04,{}, {grapple:true});assert.ok(m.grapple);run(m,2);assert.equal(m.fighters[1].hp,83);});
test('corner grapples do not teleport the attacker and throw toward the ring',()=>{for(const side of ['left','right']){const m=setup();const a=m.fighters[0],b=m.fighters[1];a.x=side==='left'?LEFT+10:RIGHT-10;b.x=a.x+(side==='left'?85:-85);const before=a.x;m.step([{...emptyInput(),grapple:true},emptyInput()]);assert.equal(a.x,before);assert.ok(Math.abs(b.x-a.x)<=85);run(m,2);assert.ok(side==='left'?b.x>a.x:b.x<a.x);assert.equal(b.z,0);}});
test('pressing both escape buttons together does not cheat the pin meter',()=>{const m=setup();close(m);m.fighters[1].state='down';m.fighters[1].downTime=4;m.fighters[1].hp=12;run(m,.02,{grapple:true});for(let i=0;i<10;i++){run(m,.04,{}, {light:true,heavy:true});run(m,.04);}assert.ok(m.pin);assert.equal(m.pin.escape,0);});
test('an active throw settles before the time limit decides the round',()=>{const m=setup();close(m);run(m,.02,{grapple:true});run(m,.6);m.remaining=.01;run(m,.05);assert.equal(m.phase,'fight');assert.ok(m.grapple);run(m,2);assert.equal(m.phase,'roundEnd');assert.ok(m.fighters.every(f=>f.z===0&&f.vz===0));assert.equal(m.method,'TIME LIMIT');});
test('time limit clears unfinished attack and airborne states',()=>{const m=setup();m.fighters[0].z=200;m.fighters[0].state='jump';m.fighters[0].vz=200;m.remaining=.01;m.step();assert.ok(m.fighters.every(f=>f.z===0&&f.vz===0&&f.move===null));});
test('standing collision remains separated at a ring boundary',()=>{const m=setup();m.fighters[0].x=LEFT;m.fighters[1].x=LEFT+20;run(m,.1);assert.ok(m.fighters[1].x-m.fighters[0].x>=66);assert.equal(m.fighters[0].x,LEFT);});
