import test from 'node:test';
import assert from 'node:assert/strict';
import {InputState} from '../dist/src/input.js';
import {Match,emptyInput} from '../dist/src/engine.js';
const pad=(index,buttons=[])=>({index,connected:true,axes:[0,0],buttons:Array.from({length:16},(_,i)=>({pressed:buttons.includes(i)}))});

test('a complete key tap between simulation ticks is delivered once',()=>{const input=new InputState();input.pressKey('KeyJ');input.releaseKey('KeyJ');const first=input.read()[0];assert.equal(first.light,false);assert.equal(first.pressed.light,true);assert.equal(input.read()[0].pressed.light,undefined);});
test('a latched device tap really starts a match action',()=>{const input=new InputState();const def={name:'Test',power:1,speed:1,toughness:1};const m=new Match([def,def],0,1,{mode:'local'});m.phase='fight';input.pressKey('KeyK');input.releaseKey('KeyK');m.step(input.read());assert.equal(m.fighters[0].move,'heavy');});
test('OS key repeat does not generate additional attack edges',()=>{const input=new InputState();input.pressKey('KeyJ');input.read();input.pressKey('KeyJ');const value=input.read()[0];assert.equal(value.light,true);assert.equal(value.pressed.light,undefined);});
test('two quick taps can be distinguished without a simulation tick between release and repress',()=>{const input=new InputState();input.pressKey('KeyJ');input.read();input.releaseKey('KeyJ');input.pressKey('KeyJ');assert.equal(input.read()[0].pressed.light,true);});
test('touch taps survive release and pointer cancellation removes held directions',()=>{const input=new InputState();input.pressTouch(3,'heavy');input.releaseTouch(3);assert.equal(input.read()[0].pressed.heavy,true);input.pressTouch(4,'left');assert.equal(input.read()[0].left,true);input.releaseTouch(4);assert.equal(input.read()[0].left,false);});
test('disconnecting player one never assigns player two to player one',()=>{let pauses=0;const input=new InputState(()=>pauses++);input.active=true;input.read([pad(0),pad(1)]);const value=input.read([null,pad(1,[2])]);assert.equal(value[0].light,false);assert.equal(value[1].light,true);assert.equal(pauses,1);assert.deepEqual(input.padSlots,[null,1]);input.read([pad(2),pad(1)]);assert.deepEqual(input.padSlots,[2,1]);});
test('holding Start pauses once and release permits the next pause press',()=>{let pauses=0;const input=new InputState(()=>pauses++);input.active=true;input.read([pad(0,[9])]);input.read([pad(0,[9])]);assert.equal(pauses,1);input.read([pad(0)]);input.read([pad(0,[9])]);assert.equal(pauses,2);});
test('clearing input removes pending attacks as well as held controls',()=>{const input=new InputState();input.pressKey('KeyJ');input.pressTouch(1,'right');input.clear();const value=input.read()[0];assert.equal(value.light,false);assert.equal(value.right,false);assert.deepEqual(value.pressed,{});});

test('arrow keys control player one; local WASD controls only player two',()=>{const input=new InputState();input.setMode('local');input.pressKey('ArrowRight');input.pressKey('KeyA');input.pressKey('KeyC');input.pressKey('KeyF');const [a,b]=input.read();assert.equal(a.right,true);assert.equal(a.left,false);assert.equal(a.pressed.grapple,true);assert.equal(b.left,true);assert.equal(b.right,false);assert.equal(b.pressed.light,true);});
test('solo WASD remains an alias for player one without moving player two',()=>{const input=new InputState();input.setMode('cpu');input.pressKey('KeyD');const [a,b]=input.read();assert.equal(a.right,true);assert.equal(b.right,false);input.setMode('local');assert.equal(input.read()[0].right,false);});
test('sliding a thumb changes directions and latches a diagonal jump once',()=>{const input=new InputState();input.pressTouch(1,['left']);assert.equal(input.read()[0].left,true);input.pressTouch(1,['right','jump']);const value=input.read()[0];assert.equal(value.left,false);assert.equal(value.right,true);assert.equal(value.pressed.jump,true);input.pressTouch(1,['right','jump']);assert.equal(input.read()[0].pressed.jump,undefined);input.pressTouch(1,[]);assert.equal(input.read()[0].right,false);});
test('movement and an attack can be held by different fingers; releasing one does not release the other',()=>{const input=new InputState();input.pressTouch(1,['right']);input.pressTouch(2,'heavy');input.releaseTouch(2);const a=input.read()[0];assert.equal(a.right,true);assert.equal(a.pressed.heavy,true);input.releaseTouch(1);assert.equal(input.read()[0].right,false);});
test('holding touch HIT repeats at a controlled rate and stops on cancellation',()=>{const input=new InputState();input.pressTouch(2,'light');let attacks=0;for(let i=0;i<60;i++)attacks+=Number(Boolean(input.read()[0].pressed.light));assert.equal(attacks,3);input.releaseTouch(2);for(let i=0;i<60;i++)assert.equal(input.read()[0].pressed.light,undefined);input.repeatHit=false;input.pressTouch(2,'light');input.read();for(let i=0;i<60;i++)assert.equal(input.read()[0].pressed.light,undefined);});
test('escape button alternates only on fresh taps and never auto-repeats',()=>{const input=new InputState();input.pressTouch(1,'escape');assert.equal(input.read()[0].pressed.light,true);input.pressTouch(1,'escape');input.pressTouch(2,'escape');assert.deepEqual(input.read()[0].pressed,{});for(let i=0;i<60;i++)assert.deepEqual(input.read()[0].pressed,{});input.releaseTouch(1);input.pressTouch(1,'escape');assert.equal(input.read()[0].pressed.heavy,true);});
test('clearing touch during a pin removes held HIT and preserves keyboard directions',()=>{const input=new InputState();input.pressKey('ArrowRight');input.pressTouch(1,'light');input.clearTouch();const a=input.read()[0];assert.equal(a.right,true);assert.equal(a.light,false);assert.deepEqual(a.pressed,{});});
